# Generated by Django 5.0.4 on 2024-04-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_summary_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='dream',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='elite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='higher_studies',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='normal',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='super_dream',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
