# Generated by Django 5.0.4 on 2024-04-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentdetails_dream_studentdetails_elite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='ineligible',
            field=models.IntegerField(default='21'),
            preserve_default=False,
        ),
    ]
