# Generated by Django 5.0.4 on 2024-04-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentdetails_ineligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='unplaced',
            field=models.IntegerField(default='4'),
            preserve_default=False,
        ),
    ]
